version: '3'
services:
  web:
    image: nginx:1.27.0-alpine
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - API_HOST=foobar.com
      - API_PORT=80